//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1433.
// 
#pragma warning disable 1591

namespace SAL.WSProxy.SAL.WSProxy {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSAccountSettingsSoap", Namespace="http://tempuri.org/")]
    public partial class WSAccountSettings : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetAccountSettingsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetAccountBuyingPowerOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSAccountSettings() {
            this.Url = global::SAL.WSProxy.Properties.Settings.Default.SAL_WSProxy_SAL_WSProxy_WSAccountSettings;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAccountSettingsCompletedEventHandler GetAccountSettingsCompleted;
        
        /// <remarks/>
        public event SetAccountBuyingPowerCompletedEventHandler SetAccountBuyingPowerCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAccountSettings", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AccountSettings GetAccountSettings(AccountId id) {
            object[] results = this.Invoke("GetAccountSettings", new object[] {
                        id});
            return ((AccountSettings)(results[0]));
        }
        
        /// <remarks/>
        public void GetAccountSettingsAsync(AccountId id) {
            this.GetAccountSettingsAsync(id, null);
        }
        
        /// <remarks/>
        public void GetAccountSettingsAsync(AccountId id, object userState) {
            if ((this.GetAccountSettingsOperationCompleted == null)) {
                this.GetAccountSettingsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAccountSettingsOperationCompleted);
            }
            this.InvokeAsync("GetAccountSettings", new object[] {
                        id}, this.GetAccountSettingsOperationCompleted, userState);
        }
        
        private void OnGetAccountSettingsOperationCompleted(object arg) {
            if ((this.GetAccountSettingsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAccountSettingsCompleted(this, new GetAccountSettingsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetAccountBuyingPower", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetAccountBuyingPower(AccountId id, decimal bp) {
            this.Invoke("SetAccountBuyingPower", new object[] {
                        id,
                        bp});
        }
        
        /// <remarks/>
        public void SetAccountBuyingPowerAsync(AccountId id, decimal bp) {
            this.SetAccountBuyingPowerAsync(id, bp, null);
        }
        
        /// <remarks/>
        public void SetAccountBuyingPowerAsync(AccountId id, decimal bp, object userState) {
            if ((this.SetAccountBuyingPowerOperationCompleted == null)) {
                this.SetAccountBuyingPowerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetAccountBuyingPowerOperationCompleted);
            }
            this.InvokeAsync("SetAccountBuyingPower", new object[] {
                        id,
                        bp}, this.SetAccountBuyingPowerOperationCompleted, userState);
        }
        
        private void OnSetAccountBuyingPowerOperationCompleted(object arg) {
            if ((this.SetAccountBuyingPowerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetAccountBuyingPowerCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AccountId {
        
        private string clearingIdField;
        
        private string branchIdField;
        
        /// <remarks/>
        public string ClearingId {
            get {
                return this.clearingIdField;
            }
            set {
                this.clearingIdField = value;
            }
        }
        
        /// <remarks/>
        public string BranchId {
            get {
                return this.branchIdField;
            }
            set {
                this.branchIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AccountSettings {
        
        private AccountId idField;
        
        private decimal buyingPowerField;
        
        private string nameField;
        
        private string addressField;
        
        /// <remarks/>
        public AccountId Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public decimal BuyingPower {
            get {
                return this.buyingPowerField;
            }
            set {
                this.buyingPowerField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void GetAccountSettingsCompletedEventHandler(object sender, GetAccountSettingsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAccountSettingsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAccountSettingsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AccountSettings Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AccountSettings)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void SetAccountBuyingPowerCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591